[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-c", "neofetch; exec zsh"]

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 10

[window]
padding.x = 12
padding.y = 12
decorations = "None"
opacity = 0.8

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]

[colors]
[colors.primary]
background = "#121212"
foreground = "#bebebe"
dim_foreground = "#8a8a8d"

[colors.cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.selection]
text = "CellForeground"
background = "#333333"

[colors.normal]
black = "#0b0f14"
red = "#8395a8"
green = "#698092"
yellow = "#6e88a0"
blue = "#7aa0d0"
magenta = "#8fa7c6"
cyan = "#9ec7e8"
white = "#d0d7e2"

[colors.bright]
black = "#8a8a8d"
red = "#4c5d71"
green = "#5f7b92"
yellow = "#86a2bb"
blue = "#8db8e6"
magenta = "#a9c1d8"
cyan = "#b7daf3"
white = "#eef3f8"