exec = hyprshade on vibrance
exec-once = swww-daemon
#exec-once = mpvpaper -o "loop-file mute" '*' ~/wallpapers/snowfall.mp4
exec-once = ~/.config/hypr/scripts/change_wallpaper.sh
#exec-once = zsh -c '[ -s $HOME/.current_wallpaper ] && "$HOME/.config/hypr/scripts/change_wallpaper.sh"'
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = ~/.config/waybar/launch.sh
exec-once = swaync
exec-once = eww daemon
exec-once = eww open clock

exec-once = [workspace 3 silent] spotify
#exec-once = [workspace 2 silent] discord --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
exec-once = [workspace 2 silent] discord --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=x11
#exec-once = zsh -c 'sleep 10 && qbittorrent'
exec-once = [workspace 2 silent] qbittorrent