general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    # lock_cmd = playerctl --all-players pause && pidof hyprlock || hyprlock  # pause all system audio and avoid starting multiple hyprlock instances.
    before_sleep_cmd = hyprctl                  # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# 15 minute, lock screen
listener {
    timeout = 900
    on-timeout = hyprlock
}

# 20 minute, turn off display
listener {
    timeout = 1200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# 30 minute, suspend
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
