foreground         #c1c3c5
background         #0a1218
background_opacity 1.0
cursor             #c1c3c5

active_tab_foreground     #0a1218
active_tab_background     #c1c3c5
inactive_tab_foreground   #c1c3c5
inactive_tab_background   #0a1218

active_border_color   #c1c3c5
inactive_border_color #0a1218
bell_border_color     #2C6B49

color0       #0a1218
color8       #59646d
color1       #2C6B49
color9       #2C6B49
color2       #4C6644
color10      #4C6644
color3       #108C58
color11      #108C58
color4       #199B5F
color12      #199B5F
color5       #0BAD66
color13      #0BAD66
color6       #51A55F
color14      #51A55F
color7       #c1c3c5
color15      #c1c3c5
