[colors]
background = '#0a12188e'
black = '#0a1218'
blue = '#2C6B49'
cursor = '#c1c3c5'
cyan = '#4C6644'
foreground = '#c1c3c5'
green = '#108C58'
magenta = '#199B5F'
red = '#0BAD66'
tabs = '#c1c3c5'
tabs-active = '#51A55F'
white = '#c1c3c5'
yellow = '#c1c3c5'
dim-black = '#0a12188e'
dim-blue = '#2C6B498e'
dim-cyan = '#4C66448e'
dim-foreground = '#c1c3c58e'
dim-green = '#108C588e'
dim-magenta = '#199B5F8e'
dim-red = '#0BAD668e'
dim-white = '#51A55F8e'
dim-yellow = '#c1c3c58e'
light-black = '#2C6B49'
light-blue = '#4C6644'
light-cyan = '#108C58'
light-foreground = '#199B5F'
light-green = '#0BAD66'
light-magenta = '#51A55F'
light-red = '#c1c3c5'
light-white = '#2C6B49'
light-yellow = '#4C6644'
