--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/noel/.config/wallpapers/current.jpg"

-- Special
background="#121a1b"
foreground="#c3c5c6"
cursor="#c3c5c6"

-- Colors
color0="#121a1b"
color1="#3D6446"
color2="#4C4F4F"
color3="#616561"
color4="#8C6D67"
color5="#708A67"
color6="#878C78"
color7="#c3c5c6"
color8="#5c7171"
color9="#3D6446"
color10="#4C4F4F"
color11="#616561"
color12="#8C6D67"
color13="#708A67"
color14="#878C78"
color15="#c3c5c6"
