[colors]
background = '#121a1b8e'
black = '#121a1b'
blue = '#3D6446'
cursor = '#c3c5c6'
cyan = '#4C4F4F'
foreground = '#c3c5c6'
green = '#616561'
magenta = '#8C6D67'
red = '#708A67'
tabs = '#c3c5c6'
tabs-active = '#878C78'
white = '#c3c5c6'
yellow = '#c3c5c6'
dim-black = '#121a1b8e'
dim-blue = '#3D64468e'
dim-cyan = '#4C4F4F8e'
dim-foreground = '#c3c5c68e'
dim-green = '#6165618e'
dim-magenta = '#8C6D678e'
dim-red = '#708A678e'
dim-white = '#878C788e'
dim-yellow = '#c3c5c68e'
light-black = '#3D6446'
light-blue = '#4C4F4F'
light-cyan = '#616561'
light-foreground = '#8C6D67'
light-green = '#708A67'
light-magenta = '#878C78'
light-red = '#c3c5c6'
light-white = '#3D6446'
light-yellow = '#4C4F4F'
