# Shell variables
# Generated by 'wal'
wallpaper="/home/noel/.config/wallpapers/current.jpg"

# Special
background='#0a1218'
foreground='#c1c3c5'
cursor='#c1c3c5'

# Colors
color0='#0a1218'
color1='#2C6B49'
color2='#4C6644'
color3='#108C58'
color4='#199B5F'
color5='#0BAD66'
color6='#51A55F'
color7='#c1c3c5'
color8='#59646d'
color9='#2C6B49'
color10='#4C6644'
color11='#108C58'
color12='#199B5F'
color13='#0BAD66'
color14='#51A55F'
color15='#c1c3c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
