# Shell variables
# Generated by 'wal'
wallpaper="/home/noel/.config/wallpapers/current.jpg"

# Special
background='#121a1b'
foreground='#c3c5c6'
cursor='#c3c5c6'

# Colors
color0='#121a1b'
color1='#3D6446'
color2='#4C4F4F'
color3='#616561'
color4='#8C6D67'
color5='#708A67'
color6='#878C78'
color7='#c3c5c6'
color8='#5c7171'
color9='#3D6446'
color10='#4C4F4F'
color11='#616561'
color12='#8C6D67'
color13='#708A67'
color14='#878C78'
color15='#c3c5c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
