--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/noel/.config/wallpapers/current.jpg"

-- Special
background="#0a1218"
foreground="#c1c3c5"
cursor="#c1c3c5"

-- Colors
color0="#0a1218"
color1="#2C6B49"
color2="#4C6644"
color3="#108C58"
color4="#199B5F"
color5="#0BAD66"
color6="#51A55F"
color7="#c1c3c5"
color8="#59646d"
color9="#2C6B49"
color10="#4C6644"
color11="#108C58"
color12="#199B5F"
color13="#0BAD66"
color14="#51A55F"
color15="#c1c3c5"
