# pywal theme for ghostty

background = 0a1218
foreground = c1c3c5
cursor-color = c1c3c5
selection-background = c1c3c5
selection-foreground = 0a1218

palette = 0=#0a1218
palette = 1=#2C6B49
palette = 2=#4C6644
palette = 3=#108C58
palette = 4=#199B5F
palette = 5=#0BAD66
palette = 6=#51A55F
palette = 7=#c1c3c5
palette = 8=#59646d
palette = 9=#2C6B49
palette = 10=#4C6644
palette = 11=#108C58
palette = 12=#199B5F
palette = 13=#0BAD66
palette = 14=#51A55F
palette = 15=#c1c3c5
