# pywal theme for ghostty

background = 121a1b
foreground = c3c5c6
cursor-color = c3c5c6
selection-background = c3c5c6
selection-foreground = 121a1b

palette = 0=#121a1b
palette = 1=#3D6446
palette = 2=#4C4F4F
palette = 3=#616561
palette = 4=#8C6D67
palette = 5=#708A67
palette = 6=#878C78
palette = 7=#c3c5c6
palette = 8=#5c7171
palette = 9=#3D6446
palette = 10=#4C4F4F
palette = 11=#616561
palette = 12=#8C6D67
palette = 13=#708A67
palette = 14=#878C78
palette = 15=#c3c5c6
