
[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-c", "neofetch; exec zsh"]

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 10

[window]
padding.x = 12
padding.y = 12
decorations = "None"
opacity = 0.8

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]

[general]
import = ["../../.cache/wal/colors-alacritty.toml"]
